### ISSUE TITLE
审核不通过 为什么啊

### ISSUE THREAD

**Issue by willshion** [EastWorld/wechat-app-mall#184]

**Comment by willshion** [comment]
都是照抄的

**Comment by willshion** [comment]
VM558:1 thirdScriptError 
 sdk uncaught third Error 
 kd is not defined 
 ReferenceError: kd is not defined
    at http://127.0.0.1:15884/appservice/pages/to-pay-order/index.js:23:18
    at require (http://127.0.0.1:15884/appservice/__dev__/WAService.js:1:1043245)
    at <anonymous>:87:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:15884/appservice/appservice?t=1567076226989:7259:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:15884/appservice/appservice?t=1567076226989:7271:20)
